target 'NearBusiness' do
pod 'SVProgressHUD','~> 1.1.3'
pod 'AFNetworking','~> 2.6.0'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'MJExtension'
pod 'SDAutoLayout'
pod 'HMSegmentedControl'
pod 'YYText'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'JPush'
pod 'MJRefresh'
#pod 'SDWebImage'
#图片 视频查看  环信里边也用到了
pod 'MWPhotoBrowser'
#一个浮动tf、tv
pod 'JVFloatLabeledTextField'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMap2DMap'
pod 'ImagePickerSheetViewController'
# 集成微信(完整版14.4M)
pod 'UMengUShare/Social/WeChat'
# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMengUShare/Social/QQ'
end

